/**
 * Prajwal N - Professional Portfolio
 * Headless WordPress CMS Integrated Client Script
 * Zero external JS dependencies
 */

document.addEventListener('DOMContentLoaded', () => {

    // ----------------------------------------------------
    // 1. Static Fallback Data (Strictly Prajwal's actual profile)
    //    Guarantees graceful degradation if CMS is offline.
    // ----------------------------------------------------
    const FALLBACK_PROJECTS = [
        {
            id: 'drone-detection',
            title: 'AI-Based Drone Detection and Direction Estimation System',
            technologies: 'ESP32-S3 | INMP441 | DSP',
            summary: 'Developed a portable embedded system for real-time drone detection using acoustic signal processing.',
            tags: ['ESP32-S3', 'INMP441 Microphone', 'FFT', 'MFCC', 'OLED'],
            concepts: [
                'Band-pass filtering & acoustic cross-correlation',
                'Sound classification & direction of arrival'
            ],
            content: `
                <h3>Project Overview</h3>
                <p>Developed a portable, low-power embedded surveillance system designed for real-time detection and direction estimation of commercial drones. The device captures environmental acoustics and isolates the specific frequencies generated by high-RPM drone propellers and motors.</p>
                <h3>Key Implementations</h3>
                <ul>
                    <li><strong>Acoustic Front-End:</strong> Integrated an INMP441 omnidirectional I2S digital microphone with an ESP32-S3 microcontroller to stream high-quality audio data.</li>
                    <li><strong>Signal Processing & DSP:</strong> Implemented band-pass filtering to isolate propeller sounds (typically 200Hz to 8kHz), followed by Fast Fourier Transform (FFT) analysis to generate spectral metrics.</li>
                    <li><strong>Feature Extraction:</strong> Extracted Mel-Frequency Cepstral Coefficients (MFCC) to construct acoustic templates suitable for lightweight classification.</li>
                    <li><strong>Direction of Arrival (DoA):</strong> Employed Cross-Correlation algorithms across audio channels to determine the time difference of arrival (TDOA) and estimate heading direction.</li>
                    <li><strong>Alert System:</strong> Configured a local OLED display (SSD1306) to show detection states, a piezo buzzer for physical proximity warnings, and Wi-Fi modules to broadcast alerts to central dashboards.</li>
                </ul>
                <h3>Application Scope</h3>
                <p>Tailored specifically for real-time security, site perimeter surveillance, and localized airspace warning applications where radar or optical cameras are impractical or too expensive.</p>
            `
        },
        {
            id: 'eating-assistance',
            title: 'Adaptive Eating Assistance System',
            technologies: 'ESP32 | MPU6050 | Sensors | Servos',
            summary: 'Developed an embedded assistive robotic feeding system for elderly and physically challenged individuals.',
            tags: ['ESP32', 'MPU6050 Gyro', 'IR Sensor', 'Servo Motors'],
            concepts: [
                'Real-time multi-sensor acquisition',
                'Hands-free automated motion control & feeding'
            ],
            content: `
                <h3>Project Overview</h3>
                <p>Designed and built an assistive robotic feeding arm to support hands-free eating, restoring autonomy to elderly, motor-impaired, and physically challenged individuals.</p>
                <h3>Key Implementations</h3>
                <ul>
                    <li><strong>Microcontroller Core:</strong> Programmed an ESP32 to coordinate multi-joint coordinate calculations and sensor polling cycles.</li>
                    <li><strong>Gesture Tracking:</strong> Integrated an MPU6050 accelerometer and gyroscope (head-mounted or strap-mounted) to record natural gesture tilts, allowing the user to guide the mechanical arm.</li>
                    <li><strong>Intent Triggering:</strong> Used an IR eye-blink sensor as a binary switch. The firmware filters out natural blinks, utilizing long/deliberate blinks to trigger scooping and feeding cycles.</li>
                    <li><strong>Motion Profiling:</strong> Controlled high-torque servo motors to drive the physical robotic linkages smoothly, reducing acceleration spikes and ensuring food remains stable.</li>
                </ul>
                <h3>Safety Features</h3>
                <p>Programmed motion boundary clamps and safety override thresholds. If the IR sensor detects an obstruction or the MPU6050 registers rapid movements, the controller instantly halts the servo power supply.</p>
            `
        },
        {
            id: 'vibration-tilt',
            title: 'Vibration and Tilt Measurement using MPU6050',
            technologies: 'ESP32 | Embedded Systems',
            summary: 'Developed a real-time vibration and tilt monitoring system using the MPU6050 accelerometer and gyroscope.',
            tags: ['ESP32', 'MPU6050', 'Accelerometer', 'Gyroscope'],
            concepts: [
                'Sensor signal processing and filtering',
                'Orientation estimation & vibration monitoring'
            ],
            content: `
                <h3>Project Overview</h3>
                <p>Developed a high-precision real-time telemetry node to measure mechanical vibrations and angular orientation (tilt) for structural safety and motor diagnostics.</p>
                <h3>Key Implementations</h3>
                <ul>
                    <li><strong>Sensor Integration:</strong> Interfaced an MPU6050 inertial measurement unit with an ESP32 over the I2C serial protocol.</li>
                    <li><strong>Drift Elimination:</strong> Wrote firmware filters combining raw gyroscope rates and accelerometer values to estimate tilt angles, neutralizing the cumulative drift inherent in gyros.</li>
                    <li><strong>Vibration Tracking:</strong> Sampled accelerometer registers at high frequencies to extract peak-to-peak displacement, velocity, and acceleration indices.</li>
                    <li><strong>Telemetry:</strong> Broadcasted variables via serial channels and local Wi-Fi, plotting metrics on HMI panels or graphing utilities in real-time.</li>
                </ul>
                <h3>Industrial Value</h3>
                <p>Serves as a cost-effective sensor node for heavy machinery alignment checks, tilt warning safety triggers on transport equipment, and structural health monitoring.</p>
            `
        },
        {
            id: 'plc-maintenance',
            title: 'PLC-Based Predictive Maintenance System',
            technologies: 'PLC | Industrial Automation',
            summary: 'Designed a predictive maintenance system for industrial motors by monitoring vibration and temperature.',
            tags: ['PLC Programming', 'HMI Design', 'Predictive Maintenance', 'Modbus/Telemetry'],
            concepts: [
                'Real-time fault detection algorithms',
                'Automated alarm generation & HMI monitoring'
            ],
            content: `
                <h3>Project Overview</h3>
                <p>Designed and programmed an industrial predictive maintenance system aimed at maximizing rotating motor uptime and avoiding catastrophic machinery failures.</p>
                <h3>Key Implementations</h3>
                <ul>
                    <li><strong>PLC logic:</strong> Programmed Programmable Logic Controller routines to monitor industrial sensor feeds (vibration transducers and RTD thermal sensors).</li>
                    <li><strong>Condition Monitoring:</strong> Implemented fault detection thresholds comparing operational parameters against ISO standards for motor health.</li>
                    <li><strong>Alarm Infrastructure:</strong> Formulated ladder logic routines to generate hierarchical alerts (Warning & Critical Shutdown) based on temperature gradients and velocity levels.</li>
                    <li><strong>Operator Interface:</strong> Designed a descriptive Human Machine Interface (HMI) page showing machine health indices, historical graphs, and troubleshooting procedures.</li>
                </ul>
                <h3>Project Outcomes</h3>
                <p>Provides early warning indicators for common faults like bearing wear, shaft misalignment, and stator overheating, enabling scheduled repairs and mitigating costly unplanned factory line downtime.</p>
            `
        }
    ];

    const FALLBACK_EXPERIENCE = [
        {
            id: 'exp-1',
            company: '1Xsoft Private Limited',
            role: 'Software Engineer - Intern',
            dateRange: 'August 2026 – Present',
            location: 'Mangalore, Karnataka / Hybrid',
            technologies: 'Embedded C, Python, Product Engineering, QA Testing',
            description: 'Contributing to software engineering pipelines, embedded system development, and firmware testing routines.'
        },
        {
            id: 'exp-2',
            company: 'InternPE',
            role: 'Embedded Systems Intern',
            dateRange: '2026',
            location: 'Remote',
            technologies: 'Arduino Uno, LM35 Sensor, Sensor Interfacing, Telemetry',
            description: 'Developed digital temperature monitoring solutions, calibrated analog sensors, and implemented serial communication protocols.'
        }
    ];

    // Global in-memory cache for modal details
    const projectDetailsCache = {};

    // ----------------------------------------------------
    // 2. Headless WordPress REST API Fetchers
    // ----------------------------------------------------

    /**
     * Fetch projects from WordPress REST API (/wp-json/wp/v2/projects)
     */
    async function loadProjects() {
        const grid = document.getElementById('projects-grid');
        if (!grid) return;

        const apiUrl = `${CONFIG.WORDPRESS_API_URL}${CONFIG.PROJECTS_ENDPOINT}?per_page=100&_embed=1`;

        try {
            const controller = new AbortController();
            const timeoutId = setTimeout(() => controller.abort(), CONFIG.REQUEST_TIMEOUT_MS);

            const response = await fetch(apiUrl, {
                signal: controller.signal,
                headers: { 'Accept': 'application/json' }
            });
            clearTimeout(timeoutId);

            if (!response.ok) {
                throw new Error(`WordPress API returned status ${response.status}`);
            }

            const rawPosts = await response.json();

            if (Array.isArray(rawPosts) && rawPosts.length > 0) {
                const projects = rawPosts.map(post => {
                    const title = post.title?.rendered ? decodeHtml(post.title.rendered) : 'Untitled Project';
                    const content = post.content?.rendered || '';
                    const summary = post.summary || (post.excerpt?.rendered ? stripHtml(post.excerpt.rendered) : '');
                    const technologies = post.technologies || '';
                    
                    let tags = post.tech_tags || [];
                    if (typeof tags === 'string') {
                        tags = tags.split(',').map(t => t.trim()).filter(Boolean);
                    }

                    let concepts = post.key_concepts || [];
                    if (typeof concepts === 'string') {
                        concepts = concepts.split('\n').map(c => c.trim().replace(/^[-*•]\s*/, '')).filter(Boolean);
                    }

                    return {
                        id: `wp-${post.id}`,
                        title,
                        technologies,
                        summary,
                        tags,
                        concepts,
                        content: content || `<p>${summary}</p>`,
                        github: post.github_link || '',
                        demo: post.live_demo || '',
                        featuredImage: post.featured_image_url || ''
                    };
                });

                renderProjects(projects, true);
                return;
            } else {
                console.info('No projects found in WordPress CMS. Using default profile projects.');
                renderProjects(FALLBACK_PROJECTS, false);
            }
        } catch (err) {
            console.warn(`[WordPress CMS Offline] ${err.message}. Displaying fallback projects.`);
            renderProjects(FALLBACK_PROJECTS, false);
        }
    }

    /**
     * Render Project Cards in the DOM
     */
    function renderProjects(projects, isLiveCMS) {
        const grid = document.getElementById('projects-grid');
        if (!grid) return;

        grid.innerHTML = '';

        projects.forEach(project => {
            // Cache project for technical details modal
            projectDetailsCache[project.id] = {
                title: project.title,
                meta: project.technologies,
                content: project.content,
                github: project.github,
                demo: project.demo
            };

            const card = document.createElement('article');
            card.className = 'project-card';

            const tagsHtml = (project.tags || [])
                .map(tag => `<span class="tech-tag">${escapeHtml(tag)}</span>`)
                .join('');

            const conceptsHtml = (project.concepts && project.concepts.length > 0)
                ? `<div class="project-concepts">
                       <strong>Key Technical Concepts:</strong>
                       <ul>
                           ${project.concepts.map(c => `<li>${escapeHtml(c)}</li>`).join('')}
                       </ul>
                   </div>`
                : '';

            const linksHtml = [];
            if (project.github) {
                linksHtml.push(`<a href="${escapeHtml(project.github)}" class="btn btn-outline btn-sm" target="_blank" rel="noopener noreferrer">GitHub</a>`);
            }
            if (project.demo) {
                linksHtml.push(`<a href="${escapeHtml(project.demo)}" class="btn btn-primary btn-sm" target="_blank" rel="noopener noreferrer">Live Demo</a>`);
            }

            card.innerHTML = `
                <div class="project-content">
                    <span class="project-meta">${escapeHtml(project.technologies)}</span>
                    <h3 class="project-title">${escapeHtml(project.title)}</h3>
                    <p class="project-summary">${escapeHtml(project.summary)}</p>
                    ${tagsHtml ? `<div class="project-tech-tags">${tagsHtml}</div>` : ''}
                    ${conceptsHtml}
                </div>
                <div class="project-footer">
                    <button class="btn btn-secondary btn-sm open-project-modal" data-project="${project.id}" aria-haspopup="dialog">View Technical Details</button>
                    ${linksHtml.join(' ')}
                </div>
            `;

            grid.appendChild(card);
        });

        // Rebind modal triggers for newly created project cards
        bindModalTriggers();
    }

    /**
     * Fetch work experience from WordPress REST API (/wp-json/wp/v2/experience)
     */
    async function loadExperience() {
        const timeline = document.getElementById('experience-timeline');
        if (!timeline) return;

        const apiUrl = `${CONFIG.WORDPRESS_API_URL}${CONFIG.EXPERIENCE_ENDPOINT}?per_page=100&_embed=1`;

        try {
            const controller = new AbortController();
            const timeoutId = setTimeout(() => controller.abort(), CONFIG.REQUEST_TIMEOUT_MS);

            const response = await fetch(apiUrl, {
                signal: controller.signal,
                headers: { 'Accept': 'application/json' }
            });
            clearTimeout(timeoutId);

            if (!response.ok) {
                throw new Error(`WordPress API returned status ${response.status}`);
            }

            const rawPosts = await response.json();

            if (Array.isArray(rawPosts) && rawPosts.length > 0) {
                const experiences = rawPosts.map(post => {
                    const company = post.company_name || decodeHtml(post.title?.rendered || 'Company');
                    const role = post.job_title || '';
                    const dateRange = post.date_range || '';
                    const location = post.location || '';
                    const technologies = post.technologies || '';
                    const description = post.content?.rendered ? stripHtml(post.content.rendered) : '';

                    return {
                        id: `wp-${post.id}`,
                        company,
                        role,
                        dateRange,
                        location,
                        technologies,
                        description
                    };
                });

                renderExperience(experiences);
                return;
            } else {
                console.info('No experience entries in WordPress CMS. Using default profile experience.');
                renderExperience(FALLBACK_EXPERIENCE);
            }
        } catch (err) {
            console.warn(`[WordPress CMS Offline] ${err.message}. Displaying fallback experience.`);
            renderExperience(FALLBACK_EXPERIENCE);
        }
    }

    /**
     * Render Work Experience Timeline
     */
    function renderExperience(experiences) {
        const timeline = document.getElementById('experience-timeline');
        if (!timeline) return;

        timeline.innerHTML = '';

        experiences.forEach(exp => {
            const item = document.createElement('div');
            item.className = 'timeline-item';

            const techTags = exp.technologies
                ? exp.technologies.split(',').map(t => `<span class="tech-tag">${escapeHtml(t.trim())}</span>`).join('')
                : '';

            item.innerHTML = `
                <div class="timeline-dot"></div>
                <div class="timeline-content">
                    ${exp.dateRange ? `<span class="timeline-date">${escapeHtml(exp.dateRange)}</span>` : ''}
                    <h3 class="timeline-title">${escapeHtml(exp.company)}</h3>
                    ${exp.role ? `<p class="timeline-role">${escapeHtml(exp.role)}</p>` : ''}
                    ${exp.location ? `<p class="timeline-location">${escapeHtml(exp.location)}</p>` : ''}
                    <p class="timeline-details">${escapeHtml(exp.description)}</p>
                    ${techTags ? `<div class="timeline-tech-tags">${techTags}</div>` : ''}
                </div>
            `;

            timeline.appendChild(item);
        });
    }

    // ----------------------------------------------------
    // 3. Responsive Mobile Menu Navigation
    // ----------------------------------------------------
    const menuToggle = document.querySelector('.menu-toggle');
    const navMenu = document.querySelector('.nav-menu');
    const navLinks = document.querySelectorAll('.nav-link');

    if (menuToggle && navMenu) {
        menuToggle.addEventListener('click', () => {
            const expanded = menuToggle.getAttribute('aria-expanded') === 'true';
            menuToggle.setAttribute('aria-expanded', !expanded);
            navMenu.classList.toggle('active');
        });

        navLinks.forEach(link => {
            link.addEventListener('click', () => {
                menuToggle.setAttribute('aria-expanded', 'false');
                navMenu.classList.remove('active');
            });
        });
    }

    // ----------------------------------------------------
    // 4. Active Link Highlighting on Scroll (Intersection Observer)
    // ----------------------------------------------------
    const sections = document.querySelectorAll('section');
    const observerOptions = {
        root: null,
        rootMargin: '-30% 0px -60% 0px',
        threshold: 0
    };

    const sectionObserver = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                const id = entry.target.getAttribute('id');
                navLinks.forEach(link => {
                    if (link.getAttribute('href') === `#${id}`) {
                        link.classList.add('active');
                    } else {
                        link.classList.remove('active');
                    }
                });
            }
        });
    }, observerOptions);

    sections.forEach(section => {
        sectionObserver.observe(section);
    });

    // ----------------------------------------------------
    // 5. Accessible Dialog Modal Window
    // ----------------------------------------------------
    const modal = document.getElementById('project-modal');
    const modalTitle = document.getElementById('modal-title');
    const modalMeta = document.getElementById('modal-project-meta');
    const modalContent = document.getElementById('modal-details-content');
    const modalCloseBtn = modal ? modal.querySelector('.modal-close') : null;
    let previousActiveElement = null;

    function bindModalTriggers() {
        if (!modal || !modalCloseBtn) return;

        const modalTriggerBtns = document.querySelectorAll('.open-project-modal');
        modalTriggerBtns.forEach(btn => {
            btn.addEventListener('click', () => {
                const projectId = btn.getAttribute('data-project');
                const project = projectDetailsCache[projectId];

                if (project) {
                    previousActiveElement = document.activeElement;

                    modalTitle.textContent = project.title;
                    modalMeta.textContent = project.meta;
                    modalContent.innerHTML = project.content;

                    modal.classList.add('active');
                    modal.setAttribute('aria-hidden', 'false');
                    document.body.style.overflow = 'hidden';

                    setTimeout(() => {
                        modalCloseBtn.focus();
                    }, 50);
                }
            });
        });
    }

    if (modal && modalCloseBtn) {
        const closeModal = () => {
            modal.classList.remove('active');
            modal.setAttribute('aria-hidden', 'true');
            document.body.style.overflow = '';

            if (previousActiveElement) {
                previousActiveElement.focus();
            }
        };

        modalCloseBtn.addEventListener('click', closeModal);

        modal.addEventListener('click', (e) => {
            if (e.target === modal) {
                closeModal();
            }
        });

        document.addEventListener('keydown', (e) => {
            if (!modal.classList.contains('active')) return;

            if (e.key === 'Escape') {
                closeModal();
            }

            if (e.key === 'Tab') {
                const focusables = modal.querySelectorAll('button, [tabindex="0"], a');
                if (focusables.length === 0) return;

                const firstElement = focusables[0];
                const lastElement = focusables[focusables.length - 1];

                if (e.shiftKey) {
                    if (document.activeElement === firstElement) {
                        lastElement.focus();
                        e.preventDefault();
                    }
                } else {
                    if (document.activeElement === lastElement) {
                        firstElement.focus();
                        e.preventDefault();
                    }
                }
            }
        });
    }

    // ----------------------------------------------------
    // 6. Utility Functions
    // ----------------------------------------------------
    function decodeHtml(html) {
        const txt = document.createElement('textarea');
        txt.innerHTML = html;
        return txt.value;
    }

    function stripHtml(html) {
        const tmp = document.createElement('div');
        tmp.innerHTML = html;
        return tmp.textContent || tmp.innerText || '';
    }

    function escapeHtml(str) {
        if (!str) return '';
        return String(str)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#039;');
    }

    // ----------------------------------------------------
    // 7. Initialize Dynamic CMS Fetching
    // ----------------------------------------------------
    loadProjects();
    loadExperience();
});
